export const GET_USER_WORKOUTS = 'GET_USER_WORKOUTS';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const REGISTER_USER = 'REGISTER_USER';

export const GET_EXERCISES = 'GET_EXERCISES';
export const CLEAR_EXERCISES = 'CLEAR_EXERCISES';
export const LOAD_EXERCISE = 'LOAD_EXERCISE';

export const ADD_WORKOUT = 'ADD_WORKOUT';
export const ADD_TO_WORKOUT = 'ADD_TO_WORKOUT';
export const REMOVE_FROM_WORKOUT = 'REMOVE_FROM_WORKOUT';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const NAME_WORKOUT = 'NAME_WORKOUT';
export const CLEAR_WORKOUT = 'CLEAR_WORKOUT';
export const GET_WORKOUTS = 'GET_WORKOUTS';