export const GET_USER_WORKOUTS = 'GET_USER_WORKOUTS';
export const DELETE_USER_WORKOUT = 'DELETE_USER_WORKOUT';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_EXERCISES = 'GET_EXERCISES';
export const CLEAR_EXERCISES = 'CLEAR_EXERCISES';
export const LOAD_EXERCISE = 'LOAD_EXERCISE';

export const ADD_WORKOUT = 'ADD_WORKOUT';
export const ADD_TO_WORKOUT = 'ADD_TO_WORKOUT';
export const REMOVE_FROM_WORKOUT = 'REMOVE_FROM_WORKOUT';
export const NAME_WORKOUT = 'NAME_WORKOUT';
export const CLEAR_WORKOUT = 'CLEAR_WORKOUT';
export const GET_ALL_WORKOUTS = 'GET_ALL_WORKOUTS';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const SET_MODAL_CONTENT = 'SET_MODAL_CONTENT';

export const SET_ERRORS = 'SET_ERRORS';
export const REMOVE_ERRORS = 'REMOVE_ERRORS';
export const REMOVE_ALL_ERRORS = 'REMOVE_ALL_ERRORS';
