export const GET_USER_WORKOUTS = 'GET_USER_WORKOUTS';

export const GET_EXERCISES = 'GET_EXERCISES';
export const CLEAR_EXERCISES = 'CLEAR_EXERCISES';

export const ADD_WORKOUT = 'ADD_WORKOUT';
export const ADD_TO_WORKOUT = 'ADD_TO_WORKOUT';
export const REMOVE_FROM_WORKOUT = 'REMOVE_FROM_WORKOUT';